### ISSUE TITLE
Headless rendering: mgl.Error: cannot detect the display

### ISSUE THREAD

**Issue by jbjuin** [cprogrammer1994/Headless-rendering-with-python#2]
I have troubles making this example to run on a ubuntu 14.04.3 VPS without GPU.  
I installed mesa & opengl libs, X11 dev lib.

When running the main.py file:  

```
ctx = Context.new(mgl.create_standalone_context(*size))
mgl.Error: cannot detect the display
```

Any idea to make it work ?

**Comment by szabolcsdombi** [comment]
Run `glxinfo | grep "OpenGL version"` and paste the result.

Please run:

```python
import ModernGL

try:
    ctx = ModernGL.create_standalone_context()

except ModernGL.Error as err:
    print(err.function, err.filename, err.line)
```

**Comment by szabolcsdombi** [comment]
It is possible the following snippet fails in your case:

```c++
	Display * dpy = XOpenDisplay(0);

	if (!dpy) {
		MGLError_Set("cannot detect the display");
		return context;
	}
```

**Comment by szabolcsdombi** [comment]
I did not know that calling `XOpenDisplay(0)` will only work if the `DISPLAY` environment variable is set.

Try to do the following:

```shell
export DISPLAY=:0
python3 main.py
```

> Since you have supplied a NULL display name, you need to have DISPLAY set in the environment. E.g. have export DISPLAY=:0 in your init script. ~ Similar [issue](https://www.experts-exchange.com/questions/28947256/XOpenDisplay-keep-return-NULL-even-the-X11-is-already-running.html)

**Comment by jbjuin** [comment]
I tried 10 times this export DISPLAY=:0 without success... 

but now I've got it working.
```
glxinfo | grep "OpenGL version"
OpenGL version string: 2.1 Mesa 10.1.3
```
Another problem arised:
```
File "main.py", line 19, in <module>
    vert = ctx.vertex_shader(vertex_shader_source)
  File "/home/test_headless_moderngl/local/lib/python3.4/site-packages/ModernGL/context.py", line 491, in vertex_shader
    return Shader.new(self.mglo.vertex_shader(source))
mgl.Error: GLSL Compiler failed

vertex_shader
=============
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, and 1.00 ES

```
This is something else. Do you have a clue, or should I open a new issue ?

**Comment by szabolcsdombi** [comment]
you will need at least **OpenGL 3.3**

```
root@glxinfo:~# glxinfo
Error: unable to open display
root@glxinfo:~# glxinfo -display :0.0 | grep OpenGL
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 4.0, 256 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 17.0.3
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.0.3
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.0.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
```

I am using a DigitalOcean 5$ droplet

```shell
apt update
apt install ubuntu-desktop
apt install mesa-utils
glxinfo -display :0.0 | grep OpenGL # this works fine
```

I will do a clean install on a new droplet.

**Comment by szabolcsdombi** [comment]
`export DISPLAY=:0.0` please note that `0.0` is used (I don't really know what is this number for)

```
root@glxinfo:~# export DISPLAY=:0.0
root@glxinfo:~# glxinfo | grep "OpenGL core"
OpenGL core profile version string: 3.3 (Core Profile) Mesa 17.0.3
```

**Comment by jbjuin** [comment]
OK it works with a fresh ubuntu server 16.04 install. 
Just need to
```
apt install xinit
startx
export DISPLAY=:0.0
python main.py
```

main_multisample.py says:
```
File "main_multisample.py", line 50, in <module>
    fbo1 = ctx.framebuffer(ctx.renderbuffer((512, 512), samples=4))
  File "/root/Headless-rendering-with-python/headless/lib/python3.5/site-packages/ModernGL/context.py", line 592, in framebuffer
    return Framebuffer.new(self.mglo.framebuffer(color_attachments, depth_attachment))
mgl.Error: the framebuffer is not complete (INCOMPLETE_ATTACHMENT)
```

**Comment by szabolcsdombi** [comment]
The Framebuffer is incomplete because no renderbuffer was created. (failed with `samples=4`) I will add a fix to ModernGL. The error should be different.

**note:**
You can have similar "effect" creating an 1024 x 1024 image (no multisample required) then resize it to 512 x 512

**Comment by szabolcsdombi** [comment]
I made a few examples with resize:
```python
img = img.resize(new_size, Image.LANCZOS)
```

method | result
---|---
no multisample<br>no resize | ![no-ms-no-resize](https://user-images.githubusercontent.com/11232402/27295046-de380f08-551b-11e7-978b-61da50fe77f8.png)
multisample 2x<br>no resize | ![ms-samples-2](https://user-images.githubusercontent.com/11232402/27295101-0fb9c0e4-551c-11e7-9a86-61c0e31ea6ab.png)
multisample 4x<br>no resize | ![ms-samples-4](https://user-images.githubusercontent.com/11232402/27295109-1315d764-551c-11e7-99c1-44e5a1c279e5.png)
**multisample 16x**<br>no resize | ![ms-samples-16](https://user-images.githubusercontent.com/11232402/27295110-1466fc38-551c-11e7-9ac9-cc024b53ce3a.png)
no multisample<br>resize 50% default | ![no-ms-resize-default](https://user-images.githubusercontent.com/11232402/27295115-177d03b8-551c-11e7-8a74-7cc45db40eb2.png)
no multisample<br>**resize 50% lanczos** | ![no-ms-resize-lanczos](https://user-images.githubusercontent.com/11232402/27295118-1944efc6-551c-11e7-9df3-7b09bce9ae61.png)

**Comment by szabolcsdombi** [comment]
The number of samples supported is `1` (on my droplet)

**Comment by jbjuin** [comment]
Super answer :+1: 
What worked for me is: `LIBGL_ALWAYS_SOFTWARE=1 python main.py` to force software rendering in mesa.
