### ISSUE TITLE
Where is linked the texture object to "v_text/in_text" ?

### ISSUE THREAD

**Issue by jbjuin** [cprogrammer1994/Headless-rendering-with-python#4]
A simple question: in the code I don't understand how the texture is bound to the model ? The simple mention is through shader v_text, in_text, but where do this relate to the python "texture" object ?

I don't know a lot about OpenGL, I usually work with three.js level libraries which hide away all those details.

Thanks a lot for all your answers.

**Comment by szabolcsdombi** [comment]
The vertex shader contains a sampler2D

[here](https://github.com/cprogrammer1994/Headless-rendering-with-python/blob/master/data/shader.frag#L3)

The default value is `0`

the `texture.use()` defaults to `texture.use(0)`

Hint

You can set the value using the uniforms:

```python
prog.uniforms['Texture'].value = 4
texture.use(4)
```

**Comment by jbjuin** [comment]
Okay !
