### ISSUE TITLE
Error: cannot detect the display on Ubuntu server with NVIDIA GPUs.

### ISSUE THREAD

**Issue by airalcorn2** [cprogrammer1994/Headless-rendering-with-python#7]
Hi. Thanks a lot for ModernGL! I was able to get it up and running fine on my laptop with integrated graphics, but when I tried running it on a headless server with NVIDIA GPUs I got `Error: cannot detect the display`. When I follow the steps [here](https://github.com/cprogrammer1994/ubuntu-headless-ModernGL) and run `glxinfo`, I get the following output:
```
name of display: :99.0
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  35
  Current serial number in output stream:  36
```
I suspect [this user](https://github.com/cprogrammer1994/ModernGL/issues/189) was also on a server with NVIDIA GPUs based on the fact it looks like they were using PyTorch. [This discussion](https://devtalk.nvidia.com/default/topic/1021047/linux/headless-remote-server-setup/1) seems to imply Xvnc isn't ideal for NVIDIA GPUs. Do you have any ideas on how to get ModernGL working with this setup?

**Comment by szabolcsdombi** [comment]
Hi!

I think we will need glxinfo to work first. Can you check if a driver update helps you? Is the proper driver installed? If you get glxinfo work. I think you will be able to run moderngl too.

I did a quick search for the minor opcode 151. Is [this](https://askubuntu.com/questions/893922/ubuntu-16-04-gives-x-error-of-failed-request-badvalue-integer-parameter-out-o) article relevant?

**Comment by airalcorn2** [comment]
My advisor (@anguyen8) pointed me to [this CARLA guide](https://github.com/carla-simulator/carla/blob/master/Docs/carla_headless.md) for setting up headless servers with NVIDIA GPUs and it worked for me. I wrote out all the steps below. Happy to submit a pull request to the ModernGL project if you think it'd be useful to others.
### These steps borrow heavily from the CARLA headless setup guide [here](https://github.com/carla-simulator/carla/blob/master/Docs/carla_headless.md).

1) Download and install the [NVIDIA drivers](https://www.nvidia.es/Download/index.aspx).

2) Install OpenGL.

```bash
sudo apt install freeglut3-dev mesa-utils
```

3) Download VirtualGL from [here](https://sourceforge.net/projects/virtualgl/files/) and install it. SourceForge is kind of annoying about redirects, so you have to [use a special option with `wget`](https://stackoverflow.com/a/45258959/1316276).

```bash
wget --content-disposition -c https://sourceforge.net/projects/virtualgl/files/2.6/virtualgl_2.6_amd64.deb
sudo dpkg -i virtualgl_2.6_amd64.deb
```

4) Download TurboVNC from [here](https://sourceforge.net/projects/turbovnc/files/) and install it. Same deal with `wget`.

```bash
wget --content-disposition -c https://sourceforge.net/projects/turbovnc/files/2.2/turbovnc_2.2_amd64.deb
sudo dpkg -i turbovnc_2.2_amd64.deb
```

5) Install some X.Org stuff.

```bash
sudo apt install x11-xserver-utils libxrandr-dev
```

6) Configure X.Org so that things will work without a display.

```bash
sudo nvidia-xconfig -a --use-display-device=None --virtual=1280x1024
```

7) Edit `/etc/X11/Xwrapper.config` and change `allowed_users=console` to `allowed_users=anybody` so that you don't need `sudo` for things to work.

8) Start X.Org. `7` can be replaced with any free number.

`nohup Xorg :7 &`

9) Start the VNC server using virtual display `8`.

```bash
/opt/TurboVNC/bin/vncserver :8
```

10) Verify that everything's working by running the following command (i.e., using display `8`, server `7`, and GPU `0`). It should print your OpenGL version.

```bash
DISPLAY=:8 vglrun -d :7.0 glxinfo | grep "OpenGL version"
```

11) After following all of these steps, I was still getting the error described [here](https://github.com/cprogrammer1994/ModernGL/issues/173) on ModernGL 5.0.4, so upgrade with:

```bash
pip install https://github.com/cprogrammer1994/ModernGL/archive/master.zip
```

12) Start Python with the virtual display enabled.

```bash
DISPLAY=:8 vglrun -d :7.0 python
```
